import type { Product } from "@/types/product";

// Temporary sample data - replaced by Supabase queries later
export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Classic Leather Jacket",
    slug: "classic-leather-jacket",
    description: "Soft full-grain leather with a timeless slim cut.",
    price_cents: 12900,
    currency: "usd",
    category_name: "Fashion",
    badge: "New",
  },
  {
    id: "2",
    name: "Noise-Cancelling Headphones",
    slug: "noise-cancelling-headphones",
    description: "40-hour battery and studio-grade wireless sound.",
    price_cents: 18900,
    currency: "usd",
    category_name: "Electronics",
    badge: "-20%",
  },
  {
    id: "3",
    name: "Ceramic Vase Set",
    slug: "ceramic-vase-set",
    description: "Three hand-glazed vases in matte neutral tones.",
    price_cents: 4500,
    currency: "usd",
    category_name: "Home & Living",
  },
  {
    id: "4",
    name: "Glow Serum Duo",
    slug: "glow-serum-duo",
    description: "Vitamin C and hyaluronic serum for daily radiance.",
    price_cents: 6200,
    currency: "usd",
    category_name: "Beauty",
  },
  {
    id: "5",
    name: "Trail Running Shoes",
    slug: "trail-running-shoes",
    description: "Lightweight grip and cushioning for any terrain.",
    price_cents: 9800,
    currency: "usd",
    category_name: "Sports",
    badge: "Best seller",
  },
  {
    id: "6",
    name: "Smart Fitness Watch",
    slug: "smart-fitness-watch",
    description: "Heart rate, sleep and GPS tracking on a bright display.",
    price_cents: 14900,
    currency: "usd",
    category_name: "Electronics",
  },
  {
    id: "7",
    name: "Linen Throw Blanket",
    slug: "linen-throw-blanket",
    description: "Breathable washed linen for every season.",
    price_cents: 5400,
    currency: "usd",
    category_name: "Home & Living",
  },
  {
    id: "8",
    name: "Everyday Backpack",
    slug: "everyday-backpack",
    description: "Water-resistant, with a padded laptop sleeve.",
    price_cents: 7900,
    currency: "usd",
    category_name: "Fashion",
  },
];
